LIBNAME=basicsys
SOURCES=basicsys.cc
INSTALL_LIBS=basicsys.dep
LIBDIR=$(PREFIX)/lib/openjs
CXXFLAGS += `$(SRCDIR)/bin/boost_config --cflags`
LDFLAGS += `$(SRCDIR)/bin/boost_config --libs=thread --libs=system` -ldl
MAJOR=0
MINOR=0
REVISION=20091220
VERSION=$(MAJOR).$(MINOR).$(REVISION)
