LIBNAME=ccurl
SOURCES=ccurl.cc
#INSTALL_LIBS=ccurl.dep
LIBDIR=$(PREFIX)/lib/openjs
#CXXFLAGS += `$(SRCDIR)/bin/boost_config --cflags`
#LDFLAGS += `$(SRCDIR)/bin/boost_config --libs=thread --libs=system` -ldl
MAJOR=0
MINOR=0
REVISION=20101016
VERSION=$(MAJOR).$(MINOR).$(REVISION)
