LIBNAME=basicfilesystem
SOURCES=basicfilesystem.cc
INSTALL_LIBS=basicfilesystem.dep
LIBDIR=$(PREFIX)/lib/openjs
CXXFLAGS += `$(SRCDIR)/bin/boost_config --cflags`
LDFLAGS += `$(SRCDIR)/bin/boost_config --libs=thread --libs=system` -ldl
MAJOR=0
MINOR=0
REVISION=20090330
VERSION=$(MAJOR).$(MINOR).$(REVISION)
